docs: modified ros-jazzy-sample-face-detection.postinst
Signed-off-by: chuhxie <chuhxie@qti.qualcomm.com>

diff --git a/debian/ros-jazzy-sample-face-detection.postinst b/debian/ros-jazzy-sample-face-detection.postinst
--- a/debian/ros-jazzy-sample-face-detection.postinst
+++ b/debian/ros-jazzy-sample-face-detection.postinst
@@ -1,34 +1,44 @@
 #!/bin/bash
 
-# This script is executed after the package is installed.
-# It is used to set up the environment and download necessary files.
-
-echo "start post install"
-
-model_path=/opt/model
-if [ -d "$model_path" ]; then
-    echo "model path $model_path exit."
+if [ -d "/opt/model" ]; then
+    echo "model path /opt/model exit."
 else
-    echo "model path $model_path not exit."
-    sudo mkdir $model_path    
-fi
-if [ -f "$model_path/MediaPipeFaceDetector.bin" ]; then
-    echo "model $model_path/MediaPipeFaceDetector.bin exit."
-else
-    echo "model $model_path/MediaPipeFaceDetector.bin not exit."
-    sudo wget https://huggingface.co/qualcomm/MediaPipe-Face-Detection/resolve/0dd669a326ec24a884e51b82741997299d937705/MediaPipeFaceDetector.bin -O $model_path/MediaPipeFaceDetector.bin
-fi
-if [ -f "$model_path/MediaPipeFaceLandmarkDetector.bin" ]; then
-    echo "model $model_path/MediaPipeFaceLandmarkDetector.bin exit."
-else
-    echo "model $model_path/MediaPipeFaceLandmarkDetector.bin not exit."
-    sudo wget https://huggingface.co/qualcomm/MediaPipe-Face-Detection/resolve/0dd669a326ec24a884e51b82741997299d937705/MediaPipeFaceLandmarkDetector.bin -O $model_path/MediaPipeFaceLandmarkDetector.bin
-fi
-if [ -f "$model_path/anchors_face.npy" ]; then
-    echo "anchor $model_path/anchors_face.npy exit."
-else
-    echo "anchor $model_path/anchors_palm.npy not exit."
-    sudo wget https://raw.githubusercontent.com/zmurez/MediaPipePyTorch/65f2549ba35cd61dfd29f402f6c21882a32fabb1/anchors_face.npy -O $model_path/anchors_face.npy
+    echo "model path /opt/model not exit."
+    mkdir /opt/model    
 fi
 
-echo "finish post install"
+download_file() {
+    local url=$1
+    local output_path=$2
+
+    echo "downloading ... : $url"
+    if ! wget --tries=3 --timeout=30 -q "$url" -O "$output_path"; then
+        echo "download error : $url" >&2
+        return 1
+    fi
+
+    echo "download successfully: $output_path"
+    return 0
+}
+ 
+# Download AI model
+if ! download_file \
+    "https://huggingface.co/qualcomm/MediaPipe-Face-Detection/resolve/0dd669a326ec24a884e51b82741997299d937705/MediaPipeFaceDetector.bin" \
+    "/opt/model/MediaPipeFaceDetector.bin";  then
+    echo "WARNING: could not download Sample face detection model; continuing installation without the model."
+fi
+ 
+ if ! download_file \
+    "https://huggingface.co/qualcomm/MediaPipe-Face-Detection/resolve/0dd669a326ec24a884e51b82741997299d937705/MediaPipeFaceLandmarkDetector.bin" \
+    "/opt/model/MediaPipeFaceLandmarkDetector.bin"; then
+    echo "WARNING: could not download Sample face landmark model; continuing installation without the model."
+fi
+
+# Download AI model labels
+if ! download_file \
+    "https://raw.githubusercontent.com/zmurez/MediaPipePyTorch/65f2549ba35cd61dfd29f402f6c21882a32fabb1/anchors_face.npy" \
+    "/opt/model/anchors_face.npy"; then
+    echo "WARNING: could not download anchors_face.npy; continuing installation without anchors face."
+fi
+
+echo "Post-install finished."
